/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconStudioArrowLeft: typeof import('~icons/studio/arrow-left')['default']
    IconStudioArrowRight: typeof import('~icons/studio/arrow-right')['default']
    IconStudioBolt: typeof import('~icons/studio/bolt')['default']
    IconStudioCheck: typeof import('~icons/studio/check')['default']
    IconStudioChevronRight: typeof import('~icons/studio/chevron-right')['default']
    IconStudioClock: typeof import('~icons/studio/clock')['default']
    IconStudioCopy: typeof import('~icons/studio/copy')['default']
    IconStudioCross: typeof import('~icons/studio/cross')['default']
    IconStudioDevice: typeof import('~icons/studio/device')['default']
    IconStudioDownload: typeof import('~icons/studio/download')['default']
    IconStudioEject: typeof import('~icons/studio/eject')['default']
    IconStudioExternal: typeof import('~icons/studio/external')['default']
    IconStudioGrid: typeof import('~icons/studio/grid')['default']
    IconStudioInfo: typeof import('~icons/studio/info')['default']
    IconStudioLab: typeof import('~icons/studio/lab')['default']
    IconStudioLogs: typeof import('~icons/studio/logs')['default']
    IconStudioPlay: typeof import('~icons/studio/play')['default']
    IconStudioPocket: typeof import('~icons/studio/pocket')['default']
    IconStudioRefresh: typeof import('~icons/studio/refresh')['default']
    IconStudioSearch: typeof import('~icons/studio/search')['default']
    IconStudioSettings: typeof import('~icons/studio/settings')['default']
    IconStudioShield: typeof import('~icons/studio/shield')['default']
    IconStudioSpinner: typeof import('~icons/studio/spinner')['default']
    IconStudioSpinnerCompact: typeof import('~icons/studio/spinner-compact')['default']
    IconStudioStop: typeof import('~icons/studio/stop')['default']
    IconStudioStore: typeof import('~icons/studio/store')['default']
    IconStudioTerminal: typeof import('~icons/studio/terminal')['default']
    IconStudioUsb: typeof import('~icons/studio/usb')['default']
    IconStudioWarning: typeof import('~icons/studio/warning')['default']
  }
}
