/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IconPhArrowRight: typeof import('~icons/ph/arrow-right')['default']
    IconPhArrowsClockwise: typeof import('~icons/ph/arrows-clockwise')['default']
    IconPhArrowSquareOut: typeof import('~icons/ph/arrow-square-out')['default']
    IconPhCaretDown: typeof import('~icons/ph/caret-down')['default']
    IconPhCaretLeft: typeof import('~icons/ph/caret-left')['default']
    IconPhCaretRight: typeof import('~icons/ph/caret-right')['default']
    IconPhCheck: typeof import('~icons/ph/check')['default']
    IconPhClock: typeof import('~icons/ph/clock')['default']
    IconPhCopy: typeof import('~icons/ph/copy')['default']
    IconPhDeviceMobile: typeof import('~icons/ph/device-mobile')['default']
    IconPhDownloadSimple: typeof import('~icons/ph/download-simple')['default']
    IconPhEject: typeof import('~icons/ph/eject')['default']
    IconPhFileText: typeof import('~icons/ph/file-text')['default']
    IconPhFlask: typeof import('~icons/ph/flask')['default']
    IconPhGear: typeof import('~icons/ph/gear')['default']
    IconPhInfo: typeof import('~icons/ph/info')['default']
    IconPhLightning: typeof import('~icons/ph/lightning')['default']
    IconPhMagnifyingGlass: typeof import('~icons/ph/magnifying-glass')['default']
    IconPhPackage: typeof import('~icons/ph/package')['default']
    IconPhPlayFill: typeof import('~icons/ph/play-fill')['default']
    IconPhShieldCheck: typeof import('~icons/ph/shield-check')['default']
    IconPhSquaresFour: typeof import('~icons/ph/squares-four')['default']
    IconPhStop: typeof import('~icons/ph/stop')['default']
    IconPhStorefront: typeof import('~icons/ph/storefront')['default']
    IconPhTerminalWindow: typeof import('~icons/ph/terminal-window')['default']
    IconPhUsb: typeof import('~icons/ph/usb')['default']
    IconPhWarning: typeof import('~icons/ph/warning')['default']
    IconPhX: typeof import('~icons/ph/x')['default']
    IconSvgSpinners90Ring: typeof import('~icons/svg-spinners/90-ring')['default']
    IconSvgSpinnersRingResize: typeof import('~icons/svg-spinners/ring-resize')['default']
  }
}
